# 设置的eureka端口号
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    instance-id: provider8762
    prefer-ip-address: true
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: eureka-provider

