# 设置的eureka端口号
server:
  port: 9301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    # 定时刷新本地缓存时间
    registryFetchIntervalSeconds: 5
  instance:
    instance-id: client9301
    prefer-ip-address: true
    ## 心跳间隔，5秒
    leaseRenewalIntervalInSeconds: 5
    ## 没有心跳的淘汰时间，10秒
    leaseExpirationDurationInSeconds: 10
spring:
  application:
    name: eureka-client2

#feigh自带断路器,但是默认是没有打开的
feign:
  hystrix:
    enabled: true               #打开断路器
    polling-interval-ms: 2000   #刷新间隔

