# 设置的eureka端口号
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: provider8761
    prefer-ip-address: true
    ## 心跳间隔，5秒
    leaseRenewalIntervalInSeconds: 5
    ## 没有心跳的淘汰时间，10秒
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    # 定时刷新本地缓存时间
    registryFetchIntervalSeconds: 5

spring:
  application:
    name: eureka-provider

