# 设置的eureka端口号
server:
  port: 8761
eureka:
  instance:
    hostname: provider8761.com
    instance-id: provider8761
    prefer-ip-address: true
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka8080.com:8080/eureka/,http://eureka8081.com:8081/eureka/,http://eureka8082.com:8082/eureka/
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: eureka-provider
  # 整合rabbitMq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:3306/self?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    # 这里不能用data-username,否则会连接mysql报错
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

################mapper文件位置################
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


# info配置
info:
  app.name: cloud-zhr-provider
  company.name: zhr



