# 设置的eureka端口号
server:
  port: 8080
eureka:
  instance:
    secure-port-enabled: false
    instance-id: server8080
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server

