# 设置的eureka端口号
server:
  port: 8080
eureka:
  instance:
    secure-port-enabled: false
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server

