# 设置的eureka端口号
server:
  port: 8060
eureka:
  instance:
    secure-port-enabled: false
    instance-id: config-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8080.com:8080/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZHR-BLACK/cloud-zhr
          username:
          password:
          timeout: 15
          search-paths: config-center


