# 设置的eureka端口号
server:
  port: 8082
eureka:
  instance:
    secure-port-enabled: false
    instance-id: server8082
    prefer-ip-address: true
    ## 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
    ## 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    hostname: eureka8082.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8080.com:8080/eureka/,http://eureka8081.com:8081/eureka/
## 中小规模下，自我保护模式坑比好处多，所以关闭它
  server:
    enable-self-preservation: false
    ## 主动失效检测间隔,配置成5秒
    eviction-interval-timer-in-ms: 5000
    # 禁用readOnlyCacheMap
    use-read-only-response-cache: false

spring:
  application:
    name: eureka-server2

# info配置
info:
  app.name: cloud-zhr-eureka2
  company.name: zhr

